### PR TITLE
List directory contents recursively

### PR DESCRIPTION
**Pull request by pavelkogan**
Adds a function to get all nodes recursively under a key.

### CODE REVIEW

**Comment by wereHamster** [comment]
I'm not sure if the function should automatically flatten the nodes. Maybe it's better to expose a generic function to flatten a node into a list and let the caller of `listDirectoryContentsRecursive` decide whether to use it or not.

It also may make sense to only return value nodes in the list. I don't see a use case where the directories would be useful.

In either case, the behavior should be better documented.

**Comment by pavelkogan** [comment]
There seem to be four options here:
1. Get a recursive listing, and process it similarly to `listDirectoryContents`. This returns a list of immediate children, but any of these might contain their own child nodes, which the caller is responsible for extracting. This seems somewhat incoherent and potentially surprising.
2. Return a `Maybe Node` (for the root key). This allows all children to be treated consistently, at the expense of being inconsistent with `listDirectoryContents`.
3. Return all children in a list, while removing subchildren from the nodes. Makes it harder to tell what the structure was, but is most consistent with the non-recursive version.
4. Same as 3, but keep subnodes. Nodes are duplicated, but no information is lost.

I think (3) balances the various concerns best, but I can implement one of the others if you prefer.

Regarding directory nodes, I agree that they're unlikely to be useful, but it's so trivial for the caller to filter them out, why not keep them just in case?

**Comment by wereHamster** [comment]
I don't have a strong opinion either way. If you add a better documentation of the function then I'll merge it and we can see what kind of use cases people come up in the future.

**Comment by pavelkogan** [comment]
Ok, added documentation. Let me know if you want anything else changed.

**Comment by wereHamster** [comment]
I released it as v1.0.5

**Comment by pavelkogan** [comment]
Great, thanks.

**Pull request merged**
