### PR TITLE
Watch for changes on a key

### PR DESCRIPTION
**Pull request by panosalbanis**
Added two public functions to allow watching a key for changes, either continuously or once.

### CODE REVIEW

**Comment by wereHamster** [comment]
I don't like passing the callbacks to the API functions like this. That is something which should be trivially possible with higher-level function combinators (eg. `>>=`, `runMaybeT` and as you've used, functions from the `async` package). I would much rather prefer having simple functions like `wait :: Client -> Key -> IO (Maybe Node)` and `waitIndex :: Client -> Key -> Index -> IO (Maybe Node)` (and maybe `waitRecursive` / `waitIndexRecursive` as well).

Also, the code as it is doesn't allow unregistering a watcher.

**Comment by panosalbanis** [comment]
Second attempt. Tried to follow your instructions as much as possible.

**Comment by wereHamster** [comment]
Yep, that looks much better.

**Comment by wereHamster** [comment]
I released a new version, v1.0.4. Enjoy.

**Comment by panosalbanis** [comment]
Awesome! Thank you.

**Pull request merged**
